### ISSUE TITLE
弹出界面后等一会就退出

### ISSUE THREAD

**Issue by Blaskyy** [zonyitoo/doubanfm-qt#13]
➜  ~  doubanfm-qt 
"Qt Warning - invalid keysym: dead_actute" 
Switch to channel "华语" 
Received new playlist with 5 songs 
CurrentPlaying:  
    artist:  "陈奕迅" 
    title:  "圣诞结" 
    album:  "七" 
    publicTime:  "2003" 
    company:  "英皇娱乐" 
    kbps:  5 
    like:  false 
    sid:  507939 
    subType:  "" 
[1]    9798 segmentation fault (core dumped)  doubanfm-qt

**Comment by ZeppLu** [comment]
亲测 KDE 5 中已无该问题，readme 文档该更新一下了

**Comment by zonyitoo** [comment]
Good, thanks!
