### ISSUE TITLE
编译通过，可以打开窗口，但是无法播放和点击

### ISSUE THREAD

**Issue by lixiao123** [zonyitoo/doubanfm-qt#32]
编译通过，也能打开窗口，但是什么按钮也无法点击，显示频道在红心兆赫，也无法切换，窗口中的一切状态都无法改变，什么原因呢？

**Comment by GeekZJJ** [comment]
@zonyitoo 我用KUbuntu14.04，一次都没有播放过。。列表倒是获取出来了

**Comment by zonyitoo** [comment]
@GeekZJJ 我在我的Ubuntu14.04上测试可以播放啊，难道是你没装好声音驱动？

**Comment by GeekZJJ** [comment]
@zonyitoo 我猜是kde的关系。不好意思，最近考试没怎么上来，加上gmail被墙的厉害，现在才看到。

**Comment by GeekZJJ** [comment]
@zonyitoo 声音驱动完全没问题的，其他程序运行都有声音，获取的播放地址也是对的，用mplayer可以播放

**Comment by GeekZJJ** [comment]
@zonyitoo 对了，我的是32位，会不会跟这个有关

**Comment by zonyitoo** [comment]
@GeekZJJ 装了`gstreamer0.10-fluendo-mp3`和`libpulse`包了么？

**Comment by GeekZJJ** [comment]
dpkg -l | grep gstreamer0.10
ii  gstreamer0.10-fluendo-mp3:i386             0.10.23.debian-3                              i386         Fluendo mp3 decoder GStreamer 0.10 plugin
ii  gstreamer0.10-nice:i386                    0.1.4-1                                       i386         ICE library (GStreamer 0.10 plugin)
ii  gstreamer0.10-plugins-base:i386            0.10.36-1.1ubuntu2                            i386         GStreamer plugins from the "base" set
ii  gstreamer0.10-plugins-good:i386            0.10.31-3+nmu1ubuntu5                         i386         GStreamer plugins from the "good" set
ii  gstreamer0.10-pulseaudio:i386              0.10.31-3+nmu1ubuntu5                         i386         GStreamer plugin for PulseAudio
ii  gstreamer0.10-qapt                         2.1.70-0ubuntu4.1                             i386         GStreamer plugin to install codecs using QApt
ii  gstreamer0.10-x:i386                       0.10.36-1.1ubuntu2                            i386         GStreamer plugins for X11 and Pango
ii  libgstreamer0.10-0:i386                    0.10.36-1.2ubuntu3                            i386         Core GStreamer libraries and elements
---------------------------------------------------------------------------------
 dpkg -l | grep libpulse
ii  libpulse-dev:i386                          1:4.0-0ubuntu11                               i386         PulseAudio client development headers and libraries
ii  libpulse-mainloop-glib0:i386               1:4.0-0ubuntu11                               i386         PulseAudio client libraries (glib support)
ii  libpulse0:i386                             1:4.0-0ubuntu11                               i386         PulseAudio client libraries
ii  libpulsedsp:i386                           1:4.0-0ubuntu11                               i386         PulseAudio OSS pre-load library
--------------------------------------------------------------------------------
@zonyitoo 这样是装了吗？

**Comment by zonyitoo** [comment]
@GeekZJJ 好吧，这应该是装了。但是为什么没有声音呢，奇怪了……

**Comment by coiby** [comment]
@zonyitoo  @GeekZJJ  我报过一个类似的issuse，可能要装 `libqt5multimedia5-plugins`这个包，具体可以看https://github.com/zonyitoo/doubanfm-qt/issues/19

**Comment by GeekZJJ** [comment]
@coiby @zonyitoo 装完libqt5multimedia5-plugins这个包可以播放了。不过在KUbuntu14.04表现为pluseaudio进程占用率略高（4%），应该是qt的兼容性问题吧。总体来说界面很漂亮。

**Comment by zonyitoo** [comment]
@coiby @GeekZJJ Good!!!

**Comment by arvinding123** [comment]
我的地址和列表都能获取，也都能点击，就是不能播放

**Comment by arvinding123** [comment]
到 Received new playlist with 1 songs 这里就没动了，我的是15.10

**Comment by lowy** [comment]
libqt5multimedia5-plugins这个包应该写进readme里 编译出来后也是没有声音 还找不出毛病 加上之后就正常了

**Comment by zonyitoo** [comment]
@lowy Ok. Thanks.
