### ISSUE TITLE
windows Qt 5.4.1 Qt creator 通过但是无法登陆，没有获取到音乐，请问是不是失效了？ 

### ISSUE THREAD

**Issue by chenjiancan** [zonyitoo/doubanfm-qt#37]
1. 无法登陆
2. 无法获取音乐
3. 点击切换channel 崩溃

Login with  "xxxxx@qq.com"
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error

**Comment by ckr815** [comment]
Maybe you have no *.dll in your release folder.

**Comment by zonyitoo** [comment]
`cannot call unresolved function`，可能是找不到DLL的原因

**Comment by zonyitoo** [comment]
请问解决了么？
