### ISSUE TITLE
歌词下拉框里没有歌词显示

### ISSUE THREAD

**Issue by lowy** [zonyitoo/doubanfm-qt#39]
debian8编译安装  一般运行正常 (切歌过频会闪退) 发现歌词下拉框里一直没有歌词显示 是还没有设置相应功能还是自己编译出错？？ 
ps 想重新编译安装一遍 怎么删除原程序？？

**Comment by lowy** [comment]
好吧 请无视PS  看了下install.sh 已成功删除

**Comment by zonyitoo** [comment]
没有歌词那就是没找到歌词了。
切歌过频这个问题，建议GDB先找一下原因，Qt跟系统结合经常会有一些奇怪的Bug

**Comment by zonyitoo** [comment]
已更新使用官方的歌词API
