### ISSUE TITLE
标题栏有两个关闭按钮

### ISSUE THREAD

**Issue by guoyunhe** [zonyitoo/doubanfm-qt#45]
![spectacle l19758](https://cloud.githubusercontent.com/assets/5836790/15203174/b492391c-1809-11e6-9dca-f739be8d2e89.png)

鼠标悬停展开 Channels 的时候，顶部标题栏还会变，感觉有点别扭。

还有一些视觉和交互的小意见：
1. 红心，删除，下一曲，暂停，设置等按钮的颜色，可能平时是灰色（红心是红色），鼠标悬停和点击时变成深灰色（红心是深红色）比较复合视觉习惯。浅灰色有种“此按钮不可用”的错觉。
2. 设置按钮是全局功能，可能放到边角比较合适。放在进度条上方，暂停下方，会误以为它是曲目设置。
3. Channels 按钮的悬停展开交互有点不习惯，建议和下方的 Lyric 一样点击展开。

整体上还是很喜欢这个软件的！

**Comment by zonyitoo** [comment]
感谢提意见。
1. 这些P图的事情，有兴趣的话可以提个PR哟。
2. 这个我试过放在其它地方，但都会很丑。
3. 这个我也试过，会不是很方便。

**Comment by guoyunhe** [comment]
感觉标题栏有两个关闭按钮的问题，应该是 KDE 的 Bug，在其它桌面系统里没有，还是把这个 Issue 关掉吧。

**Comment by guoyunhe** [comment]
在 KDE 汇报的 Bug <https://bugs.kde.org/show_bug.cgi?id=363098>
