### ISSUE TITLE
点击系统托盘图标时，窗口不会移到最前

### ISSUE THREAD

**Issue by guoyunhe** [zonyitoo/doubanfm-qt#49]
参考了一下其他播放器，比如 Amarok。点击系统托盘图标时，窗口恢复并提到最前。不然可能会被其它窗口挡住，不知道到哪里去了。

这样改是不是会好一些？

**Comment by zonyitoo** [comment]
我记得我以前刚开始做的时候找过相关的API，好像没找到。

**Comment by zonyitoo** [comment]
Fixed.
