### ISSUE TITLE
windows下QT5.6测试，无法登陆，第三方API被屏蔽

### ISSUE THREAD

**Issue by Hadesonly** [zonyitoo/doubanfm-qt#52]
Error occurred while authenticating:  "Error transferring https://www.douban.com/j/app/login - server replied: Forbidden"

**Comment by Hadesonly** [comment]
同样频道被屏蔽Error occured while getting channels:  "Error transferring https://www.douban.com/j/app/radio/channels - server replied: Forbidden"

**Comment by zonyitoo** [comment]
看起来可能是https证书的问题？你直接用浏览器访问 https://www.douban.com/j/app/radio/channels 可以么？

**Comment by Hadesonly** [comment]
显示403forbidden

**Comment by zonyitoo** [comment]
OS X 10.10.5测试正常，但我在Win7下测试的确是403 Forbidden，原因不明。

**Comment by Hadesonly** [comment]
意思这个API还是可以正常使用的吧

**Comment by zonyitoo** [comment]
在Windows下不能用啰

**Comment by Hadesonly** [comment]
linux环境下应该还行吧

**Comment by zonyitoo** [comment]
无回应，Close.
