### ISSUE TITLE
关于Qt5的小问题

### ISSUE THREAD

**Issue by RanchoCooper** [zonyitoo/doubanfm-qt#53]
OS: Ubuntu14.04

make的时候出错了...不知道为什么

后面一部分如下:
```
main.cpp: In function ‘int main(int, char**)’:
main.cpp:44:7: error: ‘class QApplication’ has no member named ‘setApplicationDisplayName’
     a.setApplicationDisplayName("QDoubanFM");
       ^
make: *** [release_tmp/obj/main.o] 错误 1
```

**Comment by zonyitoo** [comment]
你在用Qt4编译。

**Comment by RanchoCooper** [comment]
机子上qt4和qt5都有,那该咋切换呢

**Comment by zonyitoo** [comment]
Google吧。我在OS X上没有遇到你的这个问题。

**Comment by zeroch** [comment]
@RanchoCooper  找到qt5的位置 比如说 ~/Qt/5.4/gcc4.8/qmake 
最简单的就是直接用这个full path来跑, 或者你设置一个alias也可以呀.

**Comment by zonyitoo** [comment]
已一个月没有回应，先Close.

**Comment by RanchoCooper** [comment]
@Arch now, with out Chinese input...
Maybe due to Ubuntu preinstalled qt4&5 without my own preference
Later try agin in Arch :)
